### ISSUE TITLE
Can not open after the 2.2.0 update

### ISSUE THREAD

**Issue by techmagus** [pop-os/repoman#103]
I can no longer open repoman after the 2.2.0 update today.

OS: Pop OS! 22.04 LTS
Repoman: `2.2.0~1664819145~22.04~a1a5c1a all [installed,automatic]`
Repolib: `2.0.0~1664819154~22.04~4424a39 all [installed,automatic]`
Python: `3.10.6`

Tried:
- CTRL S
- Clicking the hamburger icon and selecting `System Software Sources…`
- `repoman` via commandline
- restarting

The error from the commandline is the following:

```
(repoman:36913): Gtk-CRITICAL **: 14:38:34.675: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/repoman/main.py", line 37, in do_activate
    self.win = Window()
  File "/usr/lib/python3/dist-packages/repoman/window.py", line 43, in __init__
    self.stack = Stack(self)
  File "/usr/lib/python3/dist-packages/repoman/stack.py", line 59, in __init__
    self.list_all = List(self)
  File "/usr/lib/python3/dist-packages/repoman/list.py", line 128, in __init__
    self.generate_entries()
  File "/usr/lib/python3/dist-packages/repoman/list.py", line 299, in generate_entries
    [source.name, source.uris[0], source.ident]
  File "/usr/lib/python3/dist-packages/repolib/source.py", line 341, in name
    self.generate_default_name()
  File "/usr/lib/python3/dist-packages/repolib/source.py", line 229, in generate_default_name
    if not self['X-Repolib-Name']:
  File "/usr/lib/python3/dist-packages/debian/deb822.py", line 491, in __getitem__
    value = self.__dict[keyi]
KeyError: 'X-Repolib-Name'
```

**Comment by unixpipecentipede** [comment]
I'm having the same cmdline error. Tried to run it through GUI (same as @techmagus), but to no avail.

**Comment by mmstick** [comment]
This will be fixed by https://github.com/pop-os/repolib/pull/50. Sorry for the trouble.
