### ISSUE TITLE
start fail

### ISSUE THREAD

**Issue by pomazanbohdan** [pop-os/repoman#119]
```
unnamed@pop-os:~$ repoman
Traceback (most recent call last):
  File "/usr/bin/repoman", line 57, in <module>
    from repoman import main
  File "/usr/lib/python3/dist-packages/repoman/main.py", line 31, in <module>
    from .window import Window
  File "/usr/lib/python3/dist-packages/repoman/window.py", line 26, in <module>
    from .dialog import ErrorDialog
  File "/usr/lib/python3/dist-packages/repoman/dialog.py", line 28, in <module>
    gi.require_version('Notify', '0.7')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 122, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Notify not available
```

COSMIC rust

**Comment by leviport** [comment]
Duplicate of https://github.com/pop-os/cosmic-epoch/issues/692

I want to leave it open though, since I couldn't decide whether to move that one to cosmic-epoch or to this repo. Now we can have both!
