### ISSUE TITLE
Repoman fails to load "Namespace Flatpak not available"

### ISSUE THREAD

**Issue by snugglej** [pop-os/repoman#60]
I just updated my Pop OS 19.10 with the latest updates and now repoman will no longer launch. When I try to launch from terminal I get this error below (full trace farther down). 
```
raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Flatpak not available
```

I see that I have flatpak_helper.py and flatpak.py installed so I don't know why I'm getting this error. Any help will be greatly appreciated. 

![image](https://user-images.githubusercontent.com/17776110/77837702-cc1cd800-7131-11ea-815e-401459cc73b9.png)

**Error Message**
`Gtk-Message: 20:15:15.964: Failed to load module "appmenu-gtk-module"
Traceback (most recent call last):
  File "/usr/bin/repoman", line 50, in <module>
    from repoman import main
  File "/usr/lib/python3/dist-packages/repoman/main.py", line 32, in <module>
    from .window import Window
  File "/usr/lib/python3/dist-packages/repoman/window.py", line 26, in <module>
    from .stack import Stack
  File "/usr/lib/python3/dist-packages/repoman/stack.py", line 27, in <module>
    from .list import List
  File "/usr/lib/python3/dist-packages/repoman/list.py", line 28, in <module>
    from .dialog import AddDialog, EditDialog, ErrorDialog, DeleteDialog
  File "/usr/lib/python3/dist-packages/repoman/dialog.py", line 31, in <module>
    from . import flatpak_helper 
  File "/usr/lib/python3/dist-packages/repoman/flatpak_helper.py", line 27, in <module>
    gi.require_version('Flatpak', '1.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Flatpak not available`

**Comment by yangxuanx** [comment]
I encountered the same problem

Traceback (most recent call last):
  File "/usr/bin/repoman", line 50, in <module>
    from repoman import main
  File "/usr/lib/python3/dist-packages/repoman/main.py", line 32, in <module>
    from .window import Window
  File "/usr/lib/python3/dist-packages/repoman/window.py", line 26, in <module>
    from .stack import Stack
  File "/usr/lib/python3/dist-packages/repoman/stack.py", line 27, in <module>
    from .list import List
  File "/usr/lib/python3/dist-packages/repoman/list.py", line 28, in <module>
    from .dialog import AddDialog, EditDialog, ErrorDialog, DeleteDialog
  File "/usr/lib/python3/dist-packages/repoman/dialog.py", line 31, in <module>
    from . import flatpak_helper
  File "/usr/lib/python3/dist-packages/repoman/flatpak_helper.py", line 27, in <module>
    gi.require_version('Flatpak', '1.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Flatpak not available

**Comment by snugglej** [comment]
@isantop I applied the patch you wrote on my computer and it succeeded in fixing my issue.

But I just wanted to bring the fact that I do have flatpak installed on my system. (See Image Below)

When I try to import the flatpak_helper.py into any python session I get the same error that I experienced. So I don't know if this is going to resolve an underlying issue with the flatpak_helper.py

![image](https://user-images.githubusercontent.com/17776110/77977612-c0fab100-72c5-11ea-8637-048c9a2abe2b.png)

**Comment by isantop** [comment]
@snugglej There are other components that are required for everything to work. We haven't done a lot of testing on this outside of 20.04, so that would be the recommended place to do all of that.

**Comment by snugglej** [comment]
@isantop What do you mean "recommend place to do all of that"? I am running your latest release that isn't in beta.

**Comment by isantop** [comment]
Right, support for Flatpak in Pop OS is not presently available for 19.10, and will be coming in 20.04 later this month.

**Comment by snugglej** [comment]
@isantop okay so even if I do have flatpak installed the helper only works in 20.04. Okay I just wouldn't expect features that were only for 20.04 to be ported to 19.10.

Thanks for your work and quick response.

**Comment by isantop** [comment]
It's just simpler to maintain a single code base and use the the environment to enable/disable supported features as-needed.
