### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by mmstick** [pop-os/repoman#78]
```
(repoman:12857): Gtk-CRITICAL **: 10:12:55.999: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/repoman/main.py", line 37, in do_activate
    self.win = Window()
  File "/usr/lib/python3/dist-packages/repoman/window.py", line 36, in __init__
    self.stack = Stack(self)
  File "/usr/lib/python3/dist-packages/repoman/stack.py", line 58, in __init__
    self.list_all = List(self)
  File "/usr/lib/python3/dist-packages/repoman/list.py", line 134, in __init__
    self.generate_entries()
  File "/usr/lib/python3/dist-packages/repoman/list.py", line 211, in generate_entries
    self.sources = repo.get_all_sources()
  File "/usr/lib/python3/dist-packages/repoman/repo.py", line 157, in get_all_sources
    source.load_from_file()
  File "/usr/lib/python3/dist-packages/repolib/legacy_deb.py", line 134, in load_from_file
    self.load_from_sources()
  File "/usr/lib/python3/dist-packages/repolib/legacy_deb.py", line 110, in load_from_sources
    self.make_names()
  File "/usr/lib/python3/dist-packages/repolib/legacy_deb.py", line 80, in make_names
    self.name = self.sources[0].make_name()
IndexError: list index out of range
```

**Comment by mmstick** [comment]
After removing some PPA `.list`s, it started working. Should have backed them up so I know what one caused it.

**Comment by geodro** [comment]
`-rw-r--r-- 1 root root    0 oct 23 22:21 graphics-drivers-ubuntu-ppa-focal.list
-rw-r--r-- 1 root root    0 oct 23 22:21 graphics-drivers-ubuntu-ppa-focal.list.save
-rw-r--r-- 1 root root    0 oct 23 22:21 saiarcot895-ubuntu-chromium-beta-focal.list
-rw-r--r-- 1 root root    0 oct 23 22:21 saiarcot895-ubuntu-chromium-beta-focal.list.save
-rw-r--r-- 1 root root    0 oct 23 22:21 xalt7x-ubuntu-chromium-deb-vaapi-focal.list
-rw-r--r-- 1 root root    0 oct 23 22:21 xalt7x-ubuntu-chromium-deb-vaapi-focal.list.save`

these are the ones that give error on my installment

**Comment by isantop** [comment]
This should be fixed with the latest version of Repolib. #84 also addresses this by listing the files which have errors in them in an error dialog.
